# -*- coding: utf-8 -*-
"""Miniprojeto_Bruna_Analise_de_Dados_T6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZFLMhnYhMHtveNJ8U7hCxUmCR11Y5H0Y

# Mini-Projeto - Análise Exploratória de Dados no Varejo

**Aluna:** Bruna Hariadni
**Turma:** Análise de Dados T6

## Objetivo

Realizar uma Análise Exploratória de Dados da base Varejo, identificando problemas de qualidade, realizando a limpeza dos dados e explorando características e padrões presentes na base.
"""

# Importação e carregamento dos dados

import pandas as pd
df = pd.read_csv("Base Varejo.csv", sep=";")

# Visualização das cinco primeiras linhas da base

df.head()

# Verificação da quantidade de linhas e colunas

df.shape

# Verificação dos nomes das colunas

df.columns

# Verificação dos tipos de dados de cada coluna

df.dtypes

"""## 2. Verificação da qualidade dos dados

Nesta etapa serão verificados possíveis problemas na base, como valores nulos, registros duplicados e inconsistências nos dados.
"""

# Verificação da quantidade de valores nulos em cada coluna

df.isnull().sum()

# Verificação da quantidade de registros duplicados

df.duplicated().sum()

# Contagem dos registros de cada categoria

df["PR_CAT"].value_counts()

# Visualização de alguns registros identificados como duplicados

df[df.duplicated()].head(10)

"""## 3. Limpeza e tratamento dos dados

Nesta etapa, serão removidas colunas sem informação útil, tratados valores inconsistentes, eliminadas duplicatas e ajustados os tipos de dados necessários para a análise.
"""

# Remoção das colunas completamente vazias e sem informações úteis para a análise

df = df.drop(columns=["Unnamed: 10", "Unnamed: 11", "Unnamed: 12", "Unnamed: 13"])
df.columns

# Substituição das categorias ausentes identificadas como "#N/D, aplicação da função com .apply e verificação da contagem com o value_counts()"

def tratar_categoria(categoria):
  if categoria == "#N/D":
    return "Sem categoria"
  else:
    return categoria
df["PR_CAT"] = df["PR_CAT"].apply(tratar_categoria)
df["PR_CAT"].value_counts()

# Armazena a quantidade de linhas antes da remoção das duplicatas

linhas_antes = len(df)

# Remove registros completamente duplicados

df = df.drop_duplicates()

# Calcula a quantidade de registros removidos

linhas_depois = len(df)
linhas_removidas = linhas_antes - linhas_depois
print("Linhas antes:", linhas_antes)
print("Linhas depois:", linhas_depois)
print("Linhas duplicadas removidas:", linhas_removidas)

# Confirma se ainda existem registros duplicados após o tratamento

df.duplicated().sum()

# Verificando se o Pandas está tratando data como object/texto

df["DATA"].dtype

# Verificando o formato visual da data

df["DATA"].head()

# Converte a coluna DATA de texto para datetime, considerando o dia na primeira posição

df["DATA"] = pd.to_datetime(df["DATA"], dayfirst=True)
df["DATA"].dtype

# Verificando o novo formato da data

df["DATA"].head()

# Verificação geral da estrutura e dos tipos de dados após a limpeza

df.info()

"""## 4. Estatística descritiva

Nesta etapa serão analisadas estatísticas descritivas da coluna CL_FHL, que representa o número de filhos dos clientes.
"""

# Verificando a quantidade de clientes que possuem 1, 2, 3 e 4 filhos / sort_index() - ordenando os números

df["CL_FHL"].value_counts().sort_index()

# Verificando a quantidade de IDs únicos

df["CL_ID"].nunique()

# Cria uma base com apenas um registro por cliente

clientes = df[["CL_ID", "CL_FHL"]].drop_duplicates()

# Verifica a quantidade de clientes únicos na nova base

clientes.shape

# Calcula a média do número de filhos dos clientes

media = clientes["CL_FHL"].mean()

# Calcula a mediana do número de filhos dos clientes

mediana = clientes["CL_FHL"].median()

print("Média:", media)
print("Mediana:", mediana)

# Calcula a moda do número de filhos dos clientes

moda = clientes["CL_FHL"].mode()
print("Moda:", moda)

# Calcula o menor número de filhos entre os clientes

minimo = clientes["CL_FHL"].min()

# Calcula o maior número de filhos entre os clientes

maximo= clientes["CL_FHL"].max()

# Conta a quantidade de registros utilizados na análise

contagem = clientes["CL_FHL"].count()

print("Mínimo:", minimo)
print("Máximo:", maximo)
print("Contagem:", contagem)

# Calcula o desvio padrão do número de filhos dos clientes

desvio_padrao = clientes["CL_FHL"].std()
print("Desvio padrão:", round(desvio_padrao, 2))

# Calcular os quartis do número de filhos dos clientes

q1 = clientes["CL_FHL"].quantile(0.25)
q2 = clientes["CL_FHL"].quantile(0.50)
q3 = clientes["CL_FHL"].quantile(0.75)

print("Q1 (25%)", q1)
print("Q2 (50%)", q2)
print("Q3 (75%)", q3)

"""## 5. Validação do identificador de compra

Nesta etapa será analisada a coluna `CO_ID`, responsável por identificar as compras realizadas. Como cada linha da base representa um item vendido, um mesmo `CO_ID` pode aparecer em vários registros quando uma compra possui mais de um produto.

A análise tem como objetivo verificar a quantidade de compras únicas e confirmar que a repetição do `CO_ID` não representa necessariamente uma duplicidade, mas diferentes itens pertencentes à mesma compra.
"""

# Verifica a quantidade de compras únicas na base

quantidade_compras = df["CO_ID"].nunique()
print("Quantidade de compras:", quantidade_compras)

# Agrupa os registros pelo identificador da compra e conta quantos itens existem em cada uma

itens_por_compra = df.groupby("CO_ID").size()
itens_por_compra.head()

# Visualiza os registros associados a uma compra específica

df[df["CO_ID"] == 1000].head(10)

"""### Validação do CO_ID

A análise confirmou que o `CO_ID` identifica uma compra e pode aparecer em vários registros, pois cada linha da base representa um item associado à compra. Foram identificadas 18.471 compras únicas.

Por exemplo, o `CO_ID 1000` possui 46 registros associados, contendo diferentes produtos. Portanto, a repetição do `CO_ID` não deve ser considerada uma duplicidade por si só.

## 6. Agrupamento e análise dos dados

Nesta etapa serão realizados agrupamentos para analisar os dados de diferentes perspectivas. O objetivo é resumir informações da base e identificar padrões relacionados às compras, aos clientes e aos produtos.
"""

# Agrupa os registros por gênero e conta a quantidade de compras únicas

compras_por_genero = df.groupby("CL_GENERO")["CO_ID"].nunique()
print(compras_por_genero)

# Agrupa os registros por categoria, conta a quantidade de itens e ordena o resultado do maior para o menor

itens_por_categoria = df.groupby("PR_CAT").size().sort_values(ascending=False)

print(itens_por_categoria)

# Agrupa os registros por gênero e compara compras e clientes únicos

compras_por_genero = df.groupby("CL_GENERO")["CO_ID"].nunique()
clientes_por_genero = df.groupby("CL_GENERO")["CL_ID"].nunique()

print("Compras por gênero:")
print(compras_por_genero)

print("\nClientes por gênero:")
print(clientes_por_genero)

# Calcula a média de compras por cliente em cada gênero

media_compras_por_cliente = round(compras_por_genero / clientes_por_genero, 2)
print("Média de compras por cliente:")
print(media_compras_por_cliente)

"""## 7. Exportação da base tratada

Após as etapas de limpeza, validação e transformação dos dados, a base tratada será exportada para um novo arquivo CSV, preservando os dados originais e permitindo o uso posterior da versão limpa.
"""

# Exporta a base tratada para um novo arquivo CSV

df.to_csv("df_limpo.csv", sep=";", index=False)

"""## 8. Conclusões e insights

Após a limpeza, validação e análise dos dados, foi possível identificar alguns padrões e características relevantes da base de varejo.

### Principais insights

- A categoria **ALIMENTOS** apresentou a maior quantidade de registros de itens, com 384.197 ocorrências, ficando bem acima das demais categorias.

- Foram identificadas **18.471 compras únicas** na base. A repetição do `CO_ID` é esperada, pois uma mesma compra pode possuir vários itens associados.

- O gênero feminino apresentou maior quantidade total de compras, com **9.615 compras**, enquanto o masculino apresentou **8.856**. Entretanto, também existem mais clientes do gênero feminino na base.

- Ao considerar a média de compras por cliente, os dois gêneros apresentaram resultados muito próximos: aproximadamente **18,53 compras por cliente no gênero feminino** e **18,41 no masculino**, indicando comportamento de frequência de compra semelhante entre os grupos.

- Em relação ao número de filhos, a média foi de aproximadamente **1,14 filho por cliente**, enquanto a mediana e a moda foram iguais a 0. Além disso, 75% dos clientes possuem até 2 filhos, indicando maior concentração nos valores mais baixos.

- Durante a etapa de limpeza foram encontrados registros duplicados, colunas completamente vazias e 3.228 registros de produtos sem categoria definida. Esses problemas reforçam a importância do tratamento e da validação dos dados antes da realização das análises.
"""